//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accela.Apps.Apis.Persistence
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApiDataContext : DbContext
    {
        public ApiDataContext()
            : base("name=ApiDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GeoCoordinate> GeoCoordinates { get; set; }
        public DbSet<GlobalEntity> GlobalEntities { get; set; }
        public DbSet<PersistedData> PersistedDatas { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<ScopeGroup> ScopeGroups { get; set; }
        public DbSet<Scope2Group> Scope2Groups { get; set; }
        public DbSet<AsyncRequestStatus> AsyncRequestStatuses { get; set; }
        public DbSet<Resource> Resources { get; set; }
    }
}
