//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accela.Apps.Apis.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoCoordinate
    {
        public System.Guid ID { get; set; }
        public System.Guid GlobalEntityID { get; set; }
        public Nullable<decimal> CoordinateX { get; set; }
        public Nullable<decimal> CoordinateY { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual GlobalEntity GlobalEntities { get; set; }
    }
}
