//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accela.Apps.Apis.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersistedData
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Namespace { get; set; }
        public string Name { get; set; }
        public string DataKey { get; set; }
        public string BlobName { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public long BlobSize { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ProductName { get; set; }
        public string Agency { get; set; }
        public string EntityType { get; set; }
    }
}
