IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Resources' AND COLUMN_NAME = 'SupportedAPIVersions')
BEGIN	
	ALTER TABLE dbo.Resources ADD [SupportedAPIVersions] [varchar](200) NULL;	
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Resources' AND COLUMN_NAME = 'Applicability')
BEGIN	
	ALTER TABLE dbo.Resources ADD [Applicability] [varchar](10) NULL;	
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Resources' AND COLUMN_NAME = 'MethodNickName')
BEGIN	
	ALTER TABLE dbo.Resources ADD [MethodNickName] [varchar](50) NULL;	
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Resources' AND COLUMN_NAME = 'SupportedAAVersions')
BEGIN	
	ALTER TABLE dbo.Resources ADD [SupportedAAVersions] [varchar](500) NULL;	
END
GO